### PR TITLE
Create HW2_2.py

### PR DESCRIPTION
**Pull request by WongPeiFong**
@rinnifox

### CODE REVIEW

**Comment by rinnifox** [comment]
Hi, good job!

I have a comment though: it seems that your code does not find IDs in the files, I can see the following string as a part of your output.
` 'database_info': 'No Uniprot or ENSEMBL IDs found in sequence descriptions.'`

This might be possible due to the fact that you are using `^` and `$` signs in your expressions - they bind your search strictly to the beginning and the end of the string, meaning the the whole string should match this expression. However, in this task you have a complex description string, and only small part of it contains a valid ID. So you should not use this signs here.
 
After removing these signs, please check the validity of base URLs you are using for Uniprot, as it seems that I'm getting `404 [Not found] `(use the tutorial from the related lecture, we had it there).

**Comment by WongPeiFong** [comment]
I think the issue is that have defined the function "find_uniprot_ensembl_ids twice" with the same name, so it does not find IDs in the files.
I Removed the ^ and $ anchors. @rinnifox

**Comment by rinnifox** [comment]
Now for ENSEMBL seems to be fine, and for Uniprot (hw_file1.fasta) I'm getting `database_info': {'Uniprot': 'Failed to fetch data from Uniprot. Status code: 404'}`. 

I'm not sure if you are using a correct uniprot endpoint. Please use one from the tutorial.

```
def get_uniprot(ids: list):
  accessions = ','.join(ids)
  endpoint = "https://rest.uniprot.org/uniprotkb/accessions"
  http_function = requests.get
  http_args = {'params': {'accessions': accessions}}
  return http_function(endpoint, **http_args)
```

**Comment by WongPeiFong** [comment]
get_uniprot is updeted. @rinnifox

**Comment by rinnifox** [comment]
Good, you can merge this PR into main.

**Pull request merged**
