### PR TITLE
Hw3

### PR DESCRIPTION
**Pull request by WongPeiFong**
Creating your custom ‘Car’ class and implementing iterators allowing to control the speed of the ‘Car’
@rinnifox

### CODE REVIEW

**Comment by rinnifox** [comment]
Hi!

It seems that unfortunately, regarding implementation of class and static methods, you've got the idea of the task not fully correct :(

Your examples are nice, but the actual task was to decide only about three given methods: 1) go_to_parking; 2) show_weather and 3) get_num_cars_on_road. Moreover, for defining those, you have to use special decorators using @ sign.

1. `get_num_cars on road` cannot be a static one, as you define `num_cars_on_road = 0` at the **class** level, and calling this variable using `Car.num_cars_on_road`. 
2. `show_weather` shouldn't be a usual method, as for this one it doesn't matter, which car it belongs to - the weather outside is always the same for any car at the same place. Moreover, I provided a code snippet for defining the actual weather using API of openmeteo, you should use this one in your code.

In the task also the detailed description of `accelerate()` and `brake()` methods was provided, while I don't see them in your code.

Please, correct your homework accordingly.

**Comment by WongPeiFong** [comment]
@rinnifox
 included the accelerate() and brake()

**Comment by rinnifox** [comment]
Ok, I see! 

It is correct now that `show_weather()` is a static method and `get_num_cars_on_road()` is a class method. But `go_to_parking()` is not a staticmethod, it is just a usual method as it depends on a car's state.

`accelerate()` and `brake()` methods should also use the Increase and Decrease Iterators as described in your HW file. Otherwise, it seems that currently these Iterators are not used in your code at all.

**Comment by WongPeiFong** [comment]
accelerate() and brake() methods now use the IncreaseSpeedIterator to increase the car's speed. @rinnifox

**Comment by rinnifox** [comment]
Ok, good.
I think this task can be considered as done at some level. You can merge this branch into main.

Please note though, that `parking()` should not be a classmethod (I described this above).

**Pull request merged**
