### PR TITLE
Create pull

### PR DESCRIPTION
**Pull request by WongPeiFong**
pull?

### CODE REVIEW

**Comment by WongPeiFong** [comment]
@rinnifox hi

**Comment by rinnifox** [comment]
Wong Pei Fong, hi!
 
Unfortunately, I cannot consider your homework as completed.

Here are my comments:
- All the files should be on HW1 directory and that one has to reside in HW1 branch (not in main). You have to clean up your main branch to initial commit state by using `git reset --hard 59989562627be550cd73ddb4562654751dc20483` and then `git push -f origin main`.
- From your commits history it is almost impossible to trace the changes that have been made to repository. So, you have to remove your HW1 and testing branches and perform the task from scratch. Remember, you should place your changes with `commit` and `push` commands, not with the numerous pull requests (those ones submit your changes to the main branch, you don't want to do this).
- Report is not in actual PDF format. Either you prepare it with a text editor like Google Docs, MS Word, Libre Office, etc, and then save it as PDF, or you have an option to prepare the report as a markdown file (.md) as some of your groupmates did. In that report you have to accurately indicate how you proceed with the task, step-by-step (it should look like your home task guidelines more or less). If you don't understand smth, you should try finding it in Git Handbook that I've shared with you in the presentation - it is very detailed. In case something is unclear you can always ask me your questions.

For now, I'm closing this pull request. Please, try to resubmit your task in a proper way until the end of this week.

**Comment by WongPeiFong** [comment]
Hi
So i need to delete all created file?
Wong

Karina Pats ***@***.***> 於 2024年3月8日 週五 下午12:50寫道：

**Comment by WongPeiFong** [comment]
I don't know how to exactly use git by terminal. There were many errors
while I tried to make a new file or do something. Also  I don't really
understand how to upload the file or download the files between local and
cloud files. I tried to clone from the URL for
WongPeiFong/ITMO_ScientificPython_2024
<https://github.com/WongPeiFong/ITMO_ScientificPython_2024> but got nothing
from the site, just an empty ITMO_ScientificPython_2024 file. So i can't
manage to figure out  the exact way to link the local computer with the
github site. Have read both instructions from git-scm.com and
docs.github.com but still can't work with this terminal.

Wong

翁培峰 ***@***.***> 於 2024年3月8日 週五 下午4:20寫道：

**Comment by WongPeiFong** [comment]
I have done the HW1 just by adding the required files on the github site
and step by step following the tasks written and changed the content
without using the git because after several hours attempting and fales  i
found out the difficulty is quite huge, maybe it is because i do not have
IT background and many terminal using are not understandable to me.
翁培峰 ***@***.***> 於 2024年3月8日 週五 下午6:56寫道：

**Comment by rinnifox** [comment]
Hi!

For such questions, I propose to communicate in telegram (or by email if it is more comfortable for you). If you fail to do smth, it is always better to contact me and to show what exactly is not working step-by step. 

Btw, here is the proper way to clone a repo: you have not to forget putting `.git` in the end of URL.

image

**Pull request closed without merging**
