### PR TITLE
Create HW2_1.py

### PR DESCRIPTION
**Pull request by WongPeiFong**

### CODE REVIEW

**Comment by rinnifox** [comment]
My comments regarding the regular expressions:

1. uniprot_pattern - this one looks good! one small correction in the end of the expression: `[A-Z][A-Z\d]\d` this pattern in the end can be repeated, check this [page](https://www.uniprot.org/help/accession_numbers).
2. ensembl_pattern - `^ENSG\d{11}$`, this one does not take into the account species info (like `MUS` in your HW example) and only one feature possible (`G` for genes). Check this [page](https://www.ensembl.org/info/genome/stable_ids/prefixes.html) to get an idea how species and features are encoded and modify your expression a little bit.

**Comment by WongPeiFong** [comment]
> My comments regarding the regular expressions:
> 
> 1. uniprot_pattern - this one looks good! one small correction in the end of the expression: `[A-Z][A-Z\d]\d` this pattern in the end can be repeated, check this [page](https://www.uniprot.org/help/accession_numbers).
> 2. ensembl_pattern - `^ENSG\d{11}$`, this one does not take into the account species info (like `MUS` in your HW example) and only one feature possible (`G` for genes). Check this [page](https://www.ensembl.org/info/genome/stable_ids/prefixes.html) to get an idea how species and features are encoded and modify your expression a little bit.

Regular expression patterns for matching IDs for each database is changed @rinnifox

**Comment by rinnifox** [comment]
Hmmm, your original Uniprot expression `^[OPQ][0-9][A-Z0-9]{3}[0-9]|[A-NR-Z]\d[A-Z][A-Z\d]\d$` seemed to be closer to the correct one. Now you have this `^[OPQ][0-9][A-Z0-9]{3}[0-9][A-Z][A-Z\d]\d$`, where [A-NR-Z] part is removed but it was correct. 

You had to just edit this last part: `[A-Z][A-Z\d]\d`. The proper repetition quantifiers should be inserted. Please see the illustration

image

The whole `[A-Z][A-Z\d]\d` pattern occurs one or two times. And within this pattern `[A-Z\d]` also occurs exactly two times.

For ENSEMBL, almost correct! You just have to add here `^ENS[A-Z]{3}\d{11}$` also 1-2 letters for feature prefixes (like G for Genes, T for Transcript etc).

**Comment by WongPeiFong** [comment]
For the Uniprot pattern, the last part is editted.
For the ENSEMBL pattern, the feature prefixes is included.
@rinnifox

**Comment by rinnifox** [comment]
Great! Almost there.
Let's add some small fixes upon that and I'll close this task.

Uniprot `^[OPQ][0-9][A-Z0-9]{3}[0-9]|[A-NR-Z]\d[A-Z][A-Z\d]{2}\d$` - this pattern in the end `[A-Z][A-Z\d]{2}\d` also occurs {1,2} times.

**Comment by WongPeiFong** [comment]
r'^[OPQ][0-9][A-Z0-9]{3}[0-9]|[A-NR-Z]\d[A-Z][A-Z\d]{2}\d{1,2}$'
as i understand
@rinnifox

**Comment by rinnifox** [comment]
Now it's correct! You can merge this PR by yourself :)

**Pull request merged**
